---
title: "Assignment 1: Setting up your portfolio in GitHub"
lightbox: true
format:
  html:
    toc: true
  pdf:
    documentclass: article
---

# The big picture

Remember that the final goal is to have a GitHub repository where you can showcase your work. Assignment 1 is therefore to create the repository that you will use throughout the class.

# This assignment

**Task:** Create a new repository to contain your portfolio

Specifically:

1. Create a GitHub repository for your portfolio (I suggest you call it `portfolio`)
  a. The repository should be public, or shared with us: [`jcvdav`](https://github.com/jcvdav) [`jreigrut`](https://github.com/jreigrut)
2. Add information to your `README.md` file
3. Make at least two meaningful commits

## Grading Rubric

- 50%: The repo exists on GitHub and can be accessed by us
- 30%: The repo has a `README.md` file with content (name, about you, about the project)
- 10%: The repo has a `.gitignore` file
- 10%: The repo has at least two commits, in addition to the default one

## Turning in your assignment

- Due Sunday, September 6, 2026 11:59 PM via Canvas
- Share your repository link via Canvas